20100422-1422 - Build recover: Added error message if magic number could not be found in original recover.exe
git-svn-id: https://svn.code.sf.net/p/freetzlinux/code@859 fc5b469a-3574-4ed2-a3ea-762ab7856fab

diff --git a/trunk/speed-to-fritz/recoversubscripts/split_header b/trunk/speed-to-fritz/recoversubscripts/split_header
--- a/trunk/speed-to-fritz/recoversubscripts/split_header
+++ b/trunk/speed-to-fritz/recoversubscripts/split_header
@@ -41,15 +41,18 @@ BOOTLOADER_MAGIC_L="40 80 90 00"
 BOOTLOADER_MAGIC_L_2="0x40809000"
 FV="0x2E30342E" #= .04.
 echo "--------------------------------------------------------------------------------"
-echo "Look for kernel start and end ..."
+echo "Looking for bootloader start kernel start and kernel end ..."
 bootloder_start_at="$(recoversubscripts/ipsr p "$BOOTLOADER_MAGIC_2" "$input_file")" || \
-bootloder_start_at=$(recoversubscripts/ipsr p "$BOOTLOADER_MAGIC_L_2" "$input_file")
+bootloder_start_at=$(recoversubscripts/ipsr p "$BOOTLOADER_MAGIC_L_2" "$input_file") || ret="1"
+kernel_end_at=$(recoversubscripts/ipsr p "$FV" "$input_file") || ret="2"
+kernel_start_at=$(recoversubscripts/ipsr p "$KERNEL_MAGIC_2" "$input_file") || ret="3"
+[ "$ret" == "1" ] && echo " Bootlader magic number not found in exe file, may be original recover is broken." && exit 1
+[ "$ret" == "2" ] && echo " Kernel end (.04.) not found in exe file, may be original recover is broken." && exit 1
+[ "$ret" == "3" ] && echo " Kernel magic number not found in exe file, may be original recover is broken." && exit 1
 bootloder_start_at=$((bootloder_start_at + 1))
 echo "bootloader start at: $bootloder_start_at"
-kernel_end_at=$(recoversubscripts/ipsr p "$FV" "$input_file") && \
 kernel_end_at=$((kernel_end_at - 1))
 #echo "kernel end at: $kernel_end_at"
-kernel_start_at=$(recoversubscripts/ipsr p "$KERNEL_MAGIC_2" "$input_file")
 kernel_start_at=$((kernel_start_at + 1))
 echo "kernel start at: $kernel_start_at"
 
@@ -63,3 +66,4 @@ if [ "$kernel_end_at" == "1" ]; then
 fi
 kernel_end=$kernel_end_at
 echo "kernel end at: $kernel_end_at"
+exit 0
