20091015-1557 - Patch recover fixed, it is now possibel to make a W920 recover firmware as well.
git-svn-id: https://svn.code.sf.net/p/freetzlinux/code@594 fc5b469a-3574-4ed2-a3ea-762ab7856fab

diff --git a/trunk/patch_recover/concat_recover b/trunk/patch_recover/concat_recover
--- a/trunk/patch_recover/concat_recover
+++ b/trunk/patch_recover/concat_recover
@@ -1,15 +1,24 @@
 #!/bin/bash
-#kernl_imag_file muss ein file fuer Webintefaceupdate  sein, nicht das kernel.image fuer FTP.
-#kernl_imag_file name muss "500, 501, 701, oder 900 .image" sein 
+#kernl_imag_file muss ein file fuer Webintefaceupdate  sein.
+#kernl_imag_file name muss "500, 501, 701, 900 oder 920 .image" sein 
 input_kernel_file="701.image" 
-# Nur input_kernel_filname ist veraenderbar, da der patch auf das ausgewaehlte recover inputfile abgestimmt ist.  
+#input_kernel_file="900.image" 
+input_kernel_file="920.image" 
+# Nur input_kernel_filname ist veraenderbar, da der patch auf das ausgewaehlte recover inputfile abgestimmt ist.
 #-------------------------------------------------------------------------------------------------
 #-------------------------------------------------------------------------------------------------
 input_recover_file="fritz.box_fon_wlan_7170.04.29.recover-image.exe" 
+#for all newer 8mb boxes
+input_recover_file="FRITZ.Box_Fon_WLAN_7170.04.76.recover-image.exe"
+##or w920 
+input_recover_file="FRITZ.Box_Fon_WLAN_7270_16.AnnexB.en-de-es-it-fr.04.76.recover-image.exe"
+
 #-------------------------------------------------------------------------------------------------
-./split_image $input_kernel_file
+#./split_image $input_kernel_file
+## the same as split_image but with tar
+./extract_kernel.image $input_kernel_file
+
 ./split_recover $input_recover_file
-#kernel_dir="${input_kernel_file%.*}"
 echo "$kernel_dir"
 kernel_dir="$(basename "$input_kernel_file" | sed -r 's/(.*)\.[^\.]*/\1/')"
 mkdir -p "$kernel_dir"
@@ -23,12 +32,12 @@ echo "--------------------------------------------------------------------------
 if  `cat "./$output_dir/exe_end" | grep -q 'FRITZ!Box Fon WLAN 7170'`; then
  echo "text found"
 fi
-
-#sed -i -e 's|FRITZ!Box Fon WLAN 7170|FRITZ!Box Speedp. W900V|' "./$output_dir/recover.exe"
+if [ "${kernel_dir}" != "7570" ]; then
 sed -i -e "s|FRITZ!Box Fon WLAN 7170|FRITZ!Box Speedp. W${kernel_dir}V|g" "./$output_dir/exe_end"
-
-if ! `cat "./$output_dir/exe_end" | grep -q 'FRITZ!Box Fon WLAN 7170'`; then
- echo "text changed"
+sed -i -e "s|FRITZ!Box Fon WLAN 7170|FRITZ!Box Speedp. W${kernel_dir}V|g" "./$output_dir/recover.exe"
+sed -i -e "s|FRITZ!Box Fon WLAN 7270|FRITZ!Box Speedp. W${kernel_dir}V|g" "./$output_dir/recover.exe"
+else
+sed -i -e "s|FRITZ!Box Fon WLAN 7270|FRITZ!Box Fon WLAN 7570|g" "./$output_dir/recover.exe"
 fi
 
 echo "remove check ..."
@@ -40,13 +49,31 @@ sed -i -e 's|\x0F\x85\xFA\x01\x00\x00\x8D\x85|\x90\x90\x90\x90\x90\x90\x8D\x85|'
 sed -i -e 's|\x0F\x85\x26\x02\x00\x00\x39\x9D|\x90\x90\x90\x90\x90\x90\x39\x9D|' "./$output_dir/recover.exe"
 #Check Kenenel
 #0x1a684
-sed -i -e 's|\x74\x59\x83\xFF\xFF\x89\xBD\x60|\xEB\x59\x83\xFF\xFF\x89\xBD\x60|' "./$output_dir/recover.exe"
+sed -i -e 's|\x74\x59\x83\xFF\xFF\x89\xBD|\xEB\x59\x83\xFF\xFF\x89\xBD|' "./$output_dir/recover.exe"
+#Check CRC
+#0x18520
+rplbytes="c4 0c 85 c0 74 4a"
+[ "$rplbytes" == "$(tools/hexgrep "$rplbytes" "./$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- CRC check found!"
+
+sed -i -e 's|\xC4\x0C\x85\xC0\x74\x4A|\xC4\x0C\x85\xC0\xEB\x4A|' "./$output_dir/recover.exe"
 #NOUrladerUpdat
 #0x1a310
 #sed -i -e 's|\x73\x06\x89\x1D\x50\xB6\x8F\x00|\x73\x00\x90\x90\x50\xB6\x8F\x00|' "./$output_dir/recover.exe"
 #0x1a308
 #sed -i -e 's|\x72\x0E\x81\xFF\xE8\x03\x00\x00|\x72\x08\x81\xFF\xE8\x03\x00\x00|' "./$output_dir/recover.exe"
 
+rplbytes="90 90 90 90 90 90 8d 85"
+[ "$rplbytes" == "$(tools/hexgrep "$rplbytes" "./$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- Firmware version check removed!"
+rplbytes="90 90 90 90 90 90 39 9d"
+[ "$rplbytes" == "$(tools/hexgrep "$rplbytes" "./$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- OEM check removed!"
+rplbytes="eb 59 83 ff ff 89 bd"
+[ "$rplbytes" == "$(tools/hexgrep "$rplbytes" "./$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- Kernel check removed!"
+rplbytes="c4 0c 85 c0 eb 4a"
+[ "$rplbytes" == "$(tools/hexgrep "$rplbytes" "./$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- CRC check removed!"
+#rplbytes="73 00 90 90 50 b6 8f 00"
+#[ "$rplbytes" == "$(tools/hexgrep "$rplbytes" "./$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- Urloader update removed!"
+#rplbytes="72 08 81 ff e8 03 00 00"
+#[ "$rplbytes" == "$(tools/hexgrep "$rplbytes" "./$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- Urloader2 update removed!"
 
 
 
@@ -55,7 +82,8 @@ new_act_size=`ls -l "./$kernel_dir/kernel.image" | sed -e 's/[^0-9]/#/g' | sed -
 act_diff=$((act_size - new_act_size))
 
 echo "original size= $act_size, new size= $new_act_size, difference= $act_diff" 
-[ $act_size -gt $new_act_size ] || echo "ERROR!! new kernel image does not fit into recover.exe" 
+error_size=$((new_act_size - act_size))
+[ $act_size -gt $new_act_size ] || echo "ERROR!! new kernel image does not new recover Firmware!" 
 
 
 
@@ -72,6 +100,10 @@ cat ./$output_dir/exe_mid >>$kernel_dir/$new_output_file
 cat ./$output_dir/urlader.image >>$kernel_dir/$new_output_file
 cat ./$output_dir/exe_end >>$kernel_dir/$new_output_file
 
+if  `cat "./$kernel_dir/$new_output_file" | grep -q "FRITZ!Box Speedp. W${kernel_dir}V"`; then
+ echo "-- Text changed to; FRITZ!Box Speedp. W${kernel_dir}V"
+fi
+
 
 chmod -x ./$kernel_dir/$new_output_file
 
@@ -82,9 +114,10 @@ new_act_size=`ls -l "./$kernel_dir/$new_output_file" | sed -e 's/[^0-9]/#/g' | s
 
 echo "actual size= $act_size,  new actual size= $new_act_size" 
 echo
-[ $act_size -eq $new_act_size ] || echo "ERROR!!" 
-[ $act_size -eq $new_act_size ] && echo "Size OK!!" 
- 
+
+[ $act_size -eq $new_act_size ] || echo "ERROR! Reduce size of kernel.image by: $error_size" 
+[ $act_size -eq $new_act_size ] && echo "Size OK!" 
+
 
 
 echo "All done, Press 'ENTER' to finish"
@@ -92,7 +125,4 @@ while !(read -s);do
 	sleep 1
 done
 
-exit 0
-
-sleep 20
 exit 0
