20100828-1706 - Update to use freetz patchese as the are, for aditional freetz patches more adaptions may be nedded.
git-svn-id: https://svn.code.sf.net/p/freetzlinux/code@1021 fc5b469a-3574-4ed2-a3ea-762ab7856fab

diff --git a/trunk/speed-to-fritz/tools/freetz_patch b/trunk/speed-to-fritz/tools/freetz_patch
--- a/trunk/speed-to-fritz/tools/freetz_patch
+++ b/trunk/speed-to-fritz/tools/freetz_patch
@@ -62,7 +62,7 @@ modpatch()
 		echo2 "applying patch file $2"
 		patch ${backup}-d "$1" -p0 --no-backup-if-mismatch < "$2" 2>&1 | sed -e "s/^/${L2}/g"
 		STATUS=${PIPESTATUS[0]}
-#		echo2 "----------------------------------------------------------------------"
+		echo2 "----------------------------------------------------------------------"
 	else
 		patch ${backup}-d "$1" -p0 --no-backup-if-mismatch < "$2" > /dev/null
 		STATUS=$?
@@ -85,7 +85,7 @@ modpatch()
 			rm -f "$file.orig"
 		done
 		cd - > /dev/null
-#		echo2 "----------------------------------------------------------------------"
+		echo2 "----------------------------------------------------------------------"
 	fi
 }
 
@@ -105,7 +105,7 @@ if ! declare -F | awk '{print $3}' | grep -q error; then
 	error()
 	{
 		if [ "$1" -gt 0 ]; then
-			echo -e "ERROR: $2" 1>&2
+			echo -e "${__Y}ERROR: $2${__N}" 1>&2
 			exit $1
 		fi
 	}
