* Update speedlinux installer for ubuntu 12.4
git-svn-id: https://svn.code.sf.net/p/freetzlinux/code@1423 fc5b469a-3574-4ed2-a3ea-762ab7856fab

diff --git a/trunk/co-precise/henrynestler/tarballs/configs/etc/mount_all b/trunk/co-precise/henrynestler/tarballs/configs/etc/mount_all
--- a/trunk/co-precise/henrynestler/tarballs/configs/etc/mount_all
+++ b/trunk/co-precise/henrynestler/tarballs/configs/etc/mount_all
@@ -1,9 +1,9 @@
 #!/bin/bash
-echo " * mount ..."
 #sleep 3
 #exit 0
 rm -f /dev/disk/by-uuid/*
 #fstab bug -- do it here
+! [ -e /mnt/and ] && mkdir -p /mnt/and
 mount -t cofs 31 /mnt/and
 #get firstboot settings
 for i in $(cat /mnt/and/firstboot.1.txt  | sed 's| |_|g' | sed 's|\\|\/|g' | sed "s/\r//") ; do
@@ -18,7 +18,8 @@ User_uid=$(id ${username})
 User_uid="${User_uid:4:4}"
 ;;
 mountshare*)
-mountshare=${i#*=}
+#mountshare=${i#*=}
+mountshare=${i#*:/}
 ;;
 mountuser*)
 mountuser=${i#*=}
@@ -28,9 +29,6 @@ userpasswd=${i#*=}
 ;;
 mountpassword*)
 mountpassword=${i#*=}
-;;
-mounttype*)
-mounttype=${i#*=}
 ;;
 launcher*)
 launcher=${i#*=}
@@ -45,11 +43,47 @@ INSTALLDIR=${i#*=}
 ;;
 esac
 done
-if [ "$mounttype" = "samba" ]; then
+if [ "$mountuser" != "" ]; then
+    for i in $(cat /proc/cmdline) ; do
+    case $i in
+    DISPLAY*)
+    DISPLAY="${i#*=}"
+    #echo DISPLAY: $DISPLAY
+    [ -x /usr/bin/fping ] && WINDOS_IP=$(echo $DISPLAY | sed 's|,| |g' | fping -a)
+    ;;
+    *)
+    ;;
+    esac
+    done
+   if [ -z "$WINDOS_IP" ]; 
+	then echo "Could not mount samba becaus Windows IP is not responding!"
+   else
+    echo " * mount samba ..."
+    # Setup user accounts
+    if [ -e /lib/security/pam_smbpass.so ] && [ -e /etc/pam.d/common-password ] && 
+    ! grep -qs pam_smbpass.so /etc/pam.d/common-password 
+    then
+	# have `passwd` update samba passwords as well
+	echo 'password required /lib/security/pam_smbpass.so nullok use_authtok try_first_pass' >> /etc/pam.d/common-password
+    fi
+    echo "username=$mountuser" > /etc/smbpasswd
+    echo "password=$mountpassword" >> /etc/smbpasswd
+    chmod 600 /etc/smbpasswd
+    #umount /mnt/samba
+    #echo "mountshare: $mountshare"
+    [ -e /home/$username/Desktop/windows ] && unlink /home/$username/Desktop/windows
+    #[ -e /mnt/samba ] && rmdir -f /mnt/samba
     ! [ -e /mnt/samba ] && mkdir -p /mnt/samba
     chmod 777 /mnt/samba
-    echo  * Added mount samba /$mountshare on /mnt/win
-    mount -t cifs -o credentials=/etc/smbpasswd,iocharset=iso8859-15,uid=$User_uid,gid=$User_uid,dir_mode=0022,file_mode=0133 //$DISPLAY/$mountshare /mnt/samba
+    if mount -t cifs -o credentials=/etc/smbpasswd,iocharset=iso8859-15,uid=$User_uid,gid=$User_uid,dir_mode=0022,file_mode=0133 //$WINDOS_IP/$mountshare /mnt/samba/; then
+     echo  " * Added mount samba //$WINDOS_IP/$mountshare on /mnt/samba"
+     (cd /home/$username/Desktop; ln -s /mnt/samba/ windows)
+    fi
+  fi
+else
+    [ -e /mnt/samba ] && rmdir -f /mnt/samba
+    [ -e /home/$username/Desktop/windows ] && unlink /home/$username/Desktop/windows
+     (cd /home/$username/Desktop; ln -s /mnt/win/ windows)
 fi
 # Set setings via settings.txt
 ! [ -f /mnt/and/settings.txt ] && echo "------- Local install directory not mounted! ------\n ($INSTALLDIR/settings.txt)"
@@ -61,7 +95,7 @@ mount_cofs()
 chmod 777 $3
 #echo User_uid:${User_uid}
 mount -t cofs $4 $1 $3
-echo " * Added mount $2 on '$3'"
+[ -e $3 ] && (ls -l $3 2>&1 | grep -q 'directory' && umount $3 && rmdir $3) || echo " * Added mount $2 on '$3'"
 }
 mount_co()
 {
@@ -71,68 +105,75 @@ if [ -e /mnt/and/$2 ]; then
     mount -t ext3 $4 /dev/$1 $3 ||\
     mount -t ext4 $4 /dev/$1 $3 &&\
     echo " * Added mount $2 on '$3'"
+else
+    [ -e $3 ] && rmdir $3
 fi
 }
+echo " * mount ..."
 x=$(cat /mnt/and/settings.txt  | grep -E 'cobd|cofs' | sed '/^\#/d' | sed 's|\\|\/|g' | sed "s/\r//" | sed '/ .*/d')
 #echo "settings.txt:$x"
+for i in 0 1 2 3 4 5 6 7 8 9 0; do
+    [ -e /mnt/codb$i ] && rmdir  /mnt/codb$i
+    [ -e /mnt/cofs$i ] && rmdir  /mnt/cofs$i
+done
 for i in $x; do
 case $i in
 cobd2*)
 #--------Options------------------------ v
 #--------mountdirecrory--V
 #name----V
-mount_co "cobd2" ${i#*=} "/mnt/cobd2" "-o rw,suid,dev,exec,auto,user,async"
+mount_co "cobd2" ${i#*=} "/mnt/cobd2" "-o defaults"
 ;;
 cobd3*)
-mount_co "cobd3" ${i#*=} "/mnt/cobd3" "-o rw,suid,dev,exec,auto,user,async"
+mount_co "cobd3" ${i#*=} "/mnt/cobd3" "-o defaults"
 ;;
 cobd4*)
-mount_co "cobd4" ${i#*=} "/mnt/cobd4" "-o rw,suid,dev,exec,auto,user,async"
+mount_co "cobd4" ${i#*=} "/mnt/cobd4" "-o defaults"
 ;;
 cobd5*)
-mount_co "cobd5" ${i#*=} "/mnt/cobd5" "-o rw,suid,dev,exec,auto,user,async"
+mount_co "cobd5" ${i#*=} "/mnt/cobd5" "-o defaults"
 ;;
 cobd6*)
-mount_co "cobd6" ${i#*=} "/mnt/cobd6" "-o rw,suid,dev,exec,auto,user,async"
+mount_co "cobd6" ${i#*=} "/mnt/cobd6" "-o defaults"
 ;;
 cobd7*)
-mount_co "cobd7" ${i#*=} "/mnt/cobd7" "-o rw,suid,dev,exec,auto,user,async"
+mount_co "cobd7" ${i#*=} "/mnt/cobd7" "-o defaults"
 ;;
 cobd8*)
-mount_co "cobd8" ${i#*=} "/mnt/cobd8" "-o rw,suid,dev,exec,auto,user,async"
+mount_co "cobd8" ${i#*=} "/mnt/cobd8" "-o defaults"
 ;;
 cobd9*)
-mount_co "cobd9" ${i#*=} "/mnt/cobd9" "-o rw,suid,dev,exec,auto,user,async"
+mount_co "cobd9" ${i#*=} "/mnt/cobd9" "-o defaults"
 ;;
 cofs0*)
 mount_cofs "cofs0" ${i#*=} "/mnt/win" "-o uid=${User_uid},gid=${User_uid}"
 ;;
 cofs1*)
-mount_cofs "cofs1" ${i#*=} "/mnt/cofs1" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
+mount_cofs "cofs1" ${i#*=} "/mnt/win_c" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
 ;;
 cofs2*)
-mount_cofs "cofs2" ${i#*=} "/mnt/cofs2" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
+mount_cofs "cofs2" ${i#*=} "/mnt/win_d" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
 ;;
 cofs3*)
-mount_cofs "cofs3" ${i#*=} "/mnt/cofs3" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
+mount_cofs "cofs3" ${i#*=} "/mnt/win_e" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
 ;;
 cofs4*)
-mount_cofs "cofs4" ${i#*=} "/mnt/cofs4" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
+mount_cofs "cofs4" ${i#*=} "/mnt/win_f" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
 ;;
 cofs5*)
-mount_cofs "cofs5" ${i#*=} "/mnt/cofs5" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
+mount_cofs "cofs5" ${i#*=} "/mnt/win_g" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
 ;;
 cofs6*)
-mount_cofs "cofs6" ${i#*=} "/mnt/cofs6" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
+mount_cofs "cofs6" ${i#*=} "/mnt/win_h" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
 ;;
 cofs7*)
-mount_cofs "cofs7" ${i#*=} "/mnt/cofs7" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
+mount_cofs "cofs7" ${i#*=} "/mnt/win_i" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
 ;;
 cofs8*)
-mount_cofs "cofs8" ${i#*=} "/mnt/cofs8" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
+mount_cofs "cofs8" ${i#*=} "/mnt/win_j" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
 ;;
 cofs9*)
-mount_cofs "cofs9" ${i#*=} "/mnt/cofs9" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
+mount_cofs "cofs9" ${i#*=} "/mnt/win_k" "-o dmask=0022,fmask=0133,uid=${User_uid},gid=${User_uid}"
 ;;
 *)
 ;;
