20100304-1511 - * Update recover skripts again, both endien tapes are suported now.
git-svn-id: https://svn.code.sf.net/p/freetzlinux/code@816 fc5b469a-3574-4ed2-a3ea-762ab7856fab

diff --git a/trunk/speed-to-fritz/build_new_recover_firmware b/trunk/speed-to-fritz/build_new_recover_firmware
--- a/trunk/speed-to-fritz/build_new_recover_firmware
+++ b/trunk/speed-to-fritz/build_new_recover_firmware
@@ -1,5 +1,5 @@
 #!/bin/bash
-#orig=$SECONDS
+orig=$SECONDS
 echo "--------------------------------------------------------------------------------"
 HOMEDIR=$(pwd)
 export FWORIGDIR="Firmware.orig"
@@ -17,6 +17,7 @@ AVM_New_version="XX.XX.XX"
 TCOM_New_version="XX.XX.XX"
 #above settings are not in use if ./incl_var is included
 . ./incl_var
+RDIR="$HOMEDIR/recoversubscripts/"
 if [ "$PATCH_OEM" != "y" ]; then
     echo "Option 'Force branding' was not selectet!"
     sleep 5
@@ -43,7 +44,7 @@ RECOVERIMG7141="ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7141/x_misc/deutsch
 RECOVERIMG7150="ftp://ftp.avm.de/fritz.box/fritzfon.7150/x_misc/FRITZ.Fon_7150.AnnexB.04.71.recover-image.exe"
 RECOVERIMG7170="ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7170/x_misc/deutsch/FRITZ.Box_Fon_WLAN_7170.04.76.recover-image.exe"
 RECOVERIMG7270="ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7270/x_misc/english/FRITZ.Box_Fon_WLAN_7270_16.AnnexB.en-de-es-it-fr.04.76.recover-image.exe"
-#RECOVERIMG7270="ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7270_v3/x_misc/deutsch/fritz.box_fon_wlan_7270_v3.04.80.recover-image.exe"
+RECOVERIMG7270="ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7270_v3/x_misc/deutsch/fritz.box_fon_wlan_7270_v3.04.80.recover-image.exe"
 RECOVERIMG7390="ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7390/x_misc/deutsch/fritz.box_wlan_7390_84.04.82.recover-image.exe"
 #RECOVERIMG7270="ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7390/x_misc/deutsch/fritz.box_wlan_7390_84.04.82.recover-image.exe"
 #-------------------------------------------------------------------------------------------------
@@ -100,9 +101,7 @@ kernel_dir="$NEWDIR"
 mkdir -p "$kernel_dir"
 output_dir="$(basename "$input_recover_file" | sed -r 's/(.*)\.[^\.]*/\1/')"
 mkdir -p "$output_dir"
-#$HOMEDIR/recoversubscripts/split_image $HOMEDIR $NEWIMG $kernel_dir
-## the same as split_image but with tar
-[ "$BUILDRECOVER" = "y" ] || $HOMEDIR/recoversubscripts/extract_kernel.image $HOMEDIR $NEWIMG $kernel_dir
+[ "$BUILDRECOVER" = "y" ] || $RDIR/extract_kernel.image $HOMEDIR $NEWIMG $kernel_dir
 if ! [ -f "$kernel_dir/kernel.image" ];then
     echo "New kernel.image is missing!"
     sleep 20
@@ -113,13 +112,17 @@ if ! [ -f "$input_recover_file" ];then
     sleep 20
     exit 
 fi
-$HOMEDIR/recoversubscripts/split_recover $HOMEDIR $input_recover_file $output_dir
+(cd $RDIR
+make > /dev/null
+)
+$RDIR/split_recover $HOMEDIR $input_recover_file $output_dir
+#cp -fv "$output_dir/*" ./1
+#cp -v ./1/*  "$output_dir"
 NEWNAME=$(echo "$NEWIMG" | sed -r 's/Speedport_//' | sed -r 's/-r-/-/' | sed -r 's/_OEM-/-/' | sed -r 's/M-/-/' | sed -r 's/-sp2fr-/-/' | sed -r 's/_W...V_/_/' | sed -r 's/_Fritz_Box//' | sed -r 's/_DECT//' | sed -r 's/-0_/_/'| sed -r 's/.image//' | sed -r 's/fw_//' | sed -r 's/C_//' | cut -c-70 | sed -r "s/-$//" )-recover.exe
 #echo "new name lenght: ${#NEWNAME}"
 #echo "new name: $NEWNAME"
 new_recover_file="$kernel_dir/$NEWNAME"
-#new_recover_file="$kernel_dir/Speedport_W${SPNUM}V.recover-image.exe"
-
+new_recover_file="$kernel_dir/Speedport_W${SPNUM}V.recover-image.exe"
 [ "${SPNUM}" == "500" ] && sed -i -e "s|FRITZ!Box Fon WLAN 7170|FRITZ!Box    Sinus ${SPNUM:0:3} |g" "$output_dir/exe_start"
 [ "${SPNUM}" == "501" ] && sed -i -e "s|FRITZ!Box Fon WLAN 7170|FRITZ!Box Speedp. W${SPNUM:0:3}V|g" "$output_dir/exe_start"
 SPNUM+="X"
@@ -133,73 +136,60 @@ else
      sed -i -e "s|FRITZ!Box Fon WLAN 7170|FRITZ!Box Fon WLAN ${SPNUM:0:4}|g" "$output_dir/exe_start"
      sed -i -e "s|FRITZ!Box Fon WLAN 7270|FRITZ!Box Fon WLAN ${SPNUM:0:4}|g" "$output_dir/exe_start"
 fi
-#0x1a249
-sed -i -e 's|\x85\xC0\x59\x0F\x85\xFA\x01\x00\x00\x8D\x85|\x85\xC0\x59\x90\x90\x90\x90\x90\x90\x8D\x85|' "$output_dir/exe_start"
-#.80
-sed -i -e 's|\x85\xC0\x59\x0F\x85\xEF\x01\x00\x00\x8D\x85|\x85\xC0\x59\x90\x90\x90\x90\x90\x90\x8D\x85|' "$output_dir/exe_start"
+#sed is much faster as ipsr! for replacing!
+#example: ./ipsr/ipsr s 0x85C0590F85FA0100008D85 0x85C0590F85FA0100008D85 "$output_dir/exe_start"
 #	test eax,eax pop eax => 85 C0 59
 #	jz => 0F 85
 #sed -i -e 's| 85 C0 59     0F 85    EF 01 00 00 8D 85
-#0x1a25e
-sed -i -e 's|\x85\xC0\x59\x0F\x85\x26\x02\x00\x00\x39\x9D|\x85\xC0\x59\x90\x90\x90\x90\x90\x90\x39\x9D|' "$output_dir/exe_start"
+#comment each line is a comment for the following lines on sed 
+#0x1a249
 #.80
-sed -i -e 's|\x85\xC0\x59\x0F\x85\x20\x02\x00\x00\x39\x9D|\x85\xC0\x59\x90\x90\x90\x90\x90\x90\x39\x9D|' "$output_dir/exe_start"
-#sed -i -e 's| 85 C0 59     0F 85    20 02 00 00 39 9D
+#0x1a25e
+#.80
 #0x1a684
 #0x1a249
-sed -i -e 's|\x0F\x85\xFA\x01\x00\x00\x8D\x85|\x90\x90\x90\x90\x90\x90\x8D\x85|' "$output_dir/exe_start"
 #0x1a25e
-sed -i -e 's|\x0F\x85\x26\x02\x00\x00\x39\x9D|\x90\x90\x90\x90\x90\x90\x39\x9D|' "$output_dir/exe_start"
 #0x1a684
-sed -i -e 's|\x74\x59\x83\xFF\xFF\x89\xBD|\xEB\x59\x83\xFF\xFF\x89\xBD|' "$output_dir/exe_start"
 #0x18520
-sed -i -e 's|\xC4\x0C\x85\xC0\x74\x4A|\xC4\x0C\x85\xC0\xEB\x4A|' "$output_dir/exe_start"
 #0x1a310
-sed -i -e 's|\x73\x06\x89\x1D\x50\xB6\x8F\x00|\x73\x00\x90\x90\x50\xB6\x8F\x00|' "$output_dir/exe_start"
 #0x1a308
-sed -i -e 's|\x72\x0E\x81\xFF\xE8\x03\x00\x00|\x72\x08\x81\xFF\xE8\x03\x00\x00|' "$output_dir/exe_start"
 #.80
-sed -i -e 's|\x72\x0B\x39\x7D\x08\x73\x06\x89|\x72\x05\x39\x7D\x08\x73\x06\x89|' "$output_dir/exe_start"
 #0x1a5f0
-#Check Kernel size
 #0x1846D
-sed -i -e 's|\x77\x48\x8D\x85\x08|\xEB\x48\x8D\x85\x08|' "$output_dir/exe_start"
 #.80
-sed -i -e 's|\x77\x45\x8D\x85\x10|\xEB\x45\x8D\x85\x10|' "$output_dir/exe_start"
 #0x184C1
-sed -i -e 's|\x73\x4A\x8D\x95\x08\xFC\xFF|\xEB\x4A\x8D\x95\x08\xFC\xFF|' "$output_dir/exe_start"
 #.80
-sed -i -e 's|\x00\x3B\xC8\x73\x4A\x8D\x95|\x00\x3B\xC8\xEB\x4A\x8D\x95|' "$output_dir/exe_start"
+sed -i -e 's|\x85\xC0\x59\x0F\x85\xFA\x01\x00\x00\x8D\x85|\x85\xC0\x59\x90\x90\x90\x90\x90\x90\x8D\x85|' \
+-e 's|\x85\xC0\x59\x0F\x85\xEF\x01\x00\x00\x8D\x85|\x85\xC0\x59\x90\x90\x90\x90\x90\x90\x8D\x85|' \
+-e 's|\x85\xC0\x59\x0F\x85\x26\x02\x00\x00\x39\x9D|\x85\xC0\x59\x90\x90\x90\x90\x90\x90\x39\x9D|' \
+-e 's|\x85\xC0\x59\x0F\x85\x20\x02\x00\x00\x39\x9D|\x85\xC0\x59\x90\x90\x90\x90\x90\x90\x39\x9D|' \
+-e 's|\x0F\x85\xFA\x01\x00\x00\x8D\x85|\x90\x90\x90\x90\x90\x90\x8D\x85|' \
+-e 's|\x0F\x85\x26\x02\x00\x00\x39\x9D|\x90\x90\x90\x90\x90\x90\x39\x9D|' \
+-e 's|\x74\x59\x83\xFF\xFF\x89\xBD|\xEB\x59\x83\xFF\xFF\x89\xBD|' \
+-e 's|\xC4\x0C\x85\xC0\x74\x4A|\xC4\x0C\x85\xC0\xEB\x4A|' \
+-e 's|\x73\x06\x89\x1D\x50\xB6\x8F\x00|\x73\x00\x90\x90\x50\xB6\x8F\x00|' \
+-e 's|\x72\x0E\x81\xFF\xE8\x03\x00\x00|\x72\x08\x81\xFF\xE8\x03\x00\x00|' \
+-e 's|\x72\x0B\x39\x7D\x08\x73\x06\x89|\x72\x05\x39\x7D\x08\x73\x06\x89|' \
+-e 's|\x77\x48\x8D\x85\x08|\xEB\x48\x8D\x85\x08|' \
+-e 's|\x77\x45\x8D\x85\x10|\xEB\x45\x8D\x85\x10|' \
+-e 's|\x73\x4A\x8D\x95\x08\xFC\xFF|\xEB\x4A\x8D\x95\x08\xFC\xFF|' \
+-e 's|\x00\x3B\xC8\x73\x4A\x8D\x95|\x00\x3B\xC8\xEB\x4A\x8D\x95|' "$output_dir/exe_start"
 #0x1a5f0 .26 firmware
-#sed -i -e 's|\x73\x4A\x8D\x95\x1C\xFC\xFF\xFF\x52\x51\x50\x68\x4C\x61\x90\x00|\xEB\x4A\x8D\x95\x1C\xFC\xFF\xFF\x52\x51\x50\x68\x4C\x61\x90\x00|' "./$output_dir/exe_start"
-rplbytes="90 90 90 90 90 90 8d 85"
-[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/exe_start" | sed 's/.*://')" ] && echo "-- Firmware version check remove error!" && checkerror="y"
-rplbytes="90 90 90 90 90 90 39 9d"
-[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/exe_start" | sed 's/.*://')" ] && echo "-- OEM check remove error!" && checkerror="y"
-rplbytes="eb 59 83 ff ff 89 bd"
-[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/exe_start" | sed 's/.*://')" ] && echo "-- Kernel check remove error!" && checkerror="y"
-#rplbytes="c4 0c 85 c0 eb 4a"
-#[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/exe_start" | sed 's/.*://')" ] && echo "-- CRC check remove error!" && checkerror="y"
-#rplbytes="73 00 90 90 50 b6 8f 00"
-#[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/exe_start" | sed 's/.*://')" ] && echo "-- Urloader update remove error!" && checkerror="y"
-rplbytes="72 08 81 ff e8 03 00 00"
-rplbytes1="72 05 39 7d 08 73 06 89" 
-if ! ( [ "$rplbytes" == "$(tools/hexgrep "$rplbytes" "$output_dir/exe_start" | sed 's/.*://')" ] || \
- [ "$rplbytes1" == "$(tools/hexgrep "$rplbytes1" "$output_dir/exe_start" | sed 's/.*://')" ] ) ; then 
- echo "-- Urloader2 update remove error!" && checkerror="y"
-fi
-#rplbytes="eb 4a 8d 95 1c fc ff ff 52 51 50 68 4c 61 90 00"
-#[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/exe_start" | sed 's/.*://')" ] && echo "-- Check kernel size remove error!" && checkerror="y"
+#sed -i -e 's|734A8D951CFCFFFF525150684C619000|EB4A8D951CFCFFFF525150684C619000|' "./$output_dir/exe_start"
+$RDIR/ipsr s "0x9090909090908d85" "$output_dir/exe_start" || ( echo "-- Firmware version check remove error!" && checkerror="y" )
+$RDIR/ipsr s "0x909090909090399d" "$output_dir/exe_start" || ( echo "-- OEM check remove error!" && checkerror="y" )
+$RDIR/ipsr s "0xeb5983ffff89bd" "$output_dir/exe_start" || ( echo "-- Kernel check remove error!" && checkerror="y" )
+#$RDIR/ipsr s "0xc40c85c0eb4a" "$output_dir/exe_start" || ( echo "-- CRC check remove error!" && checkerror="y" )
+#$RDIR/ipsr   "0x7300909050b68f00" "$output_dir/exe_start" || ( echo "-- Urloader update remove error!" && checkerror="y" )
+( $RDIR/ipsr s "0x720881ffe8030000" "$output_dir/exe_start" || \
+$RDIR/ipsr s "0x7205397D08730689" "$output_dir/exe_start" ) || ( echo "-- Urloader2 update remove error!" && checkerror="y" )
+#rplbytes="0xeb4a8d951cfcffff525150684c619000"
+#$RDIR/ipsr s "0xeb4a8d951cfcffff525150684c619000" "$output_dir/exe_start" || ( echo "-- Check kernel size remove error!" && checkerror="y" )
 if ! ( [ "${R_IMG}" == "${RECOVERIMG7140}" ] || [ "${R_IMG}" == "${RECOVERIMG5050}" ] ) ; then
  {
- rplbytes="00 3b c8 eb 4a 8d 95"
- [ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/exe_start" | sed 's/.*://')" ] && echo "-- Check kernel size remove error!" && checkerror="y"
- rplbytes="eb 48 8d 85 08"
- rplbytes1="eb 45 8d 85 10"
- if ! ( [ "$rplbytes" == "$(tools/hexgrep "$rplbytes" "$output_dir/exe_start" | sed 's/.*://')" ] || \
- [ "$rplbytes1" == "$(tools/hexgrep "$rplbytes1" "$output_dir/exe_start" | sed 's/.*://')" ] ) ; then
- echo "-- Check2 kernel size remove error!" && checkerror="y"
- fi
+ $RDIR/ipsr s "0x003bc8eb4a8d95" "$output_dir/exe_start" || ( echo "-- Check kernel size remove error!" && checkerror="y" )
+ ( $RDIR/ipsr s "0xeb488d8508" "$output_dir/exe_start" || \
+ $RDIR/ipsr s "0xeb458d8510" "$output_dir/exe_start" ) ||  ( echo "-- Check2 kernel size remove error!" && checkerror="y" )
  }
 fi
 act_size=`ls -l "$output_dir/kernel.image" | sed -e 's/[^0-9]/#/g' | sed -e 's/#\+[0-9]\+#\+\([0-9]\+\).*/\1/'`
@@ -220,10 +210,10 @@ AVM_New_version="$AVM_VERSION_MAJOR.$AVM_VERSION"
 OldRversion="$(dd if=$output_dir/exe_mid bs=1 count=16  2> /dev/null)"
 OldRversion_C="$(dd if=$output_dir/exe_mid bs=1 count=16  2> /dev/null | sed 's/-//' | tr -d '[:alpha:]' | sed 's/-\.//' )"
 New_Rversion=$AVM_New_version$(dd if=$output_dir/exe_mid bs=1 count=16  2> /dev/null | sed 's/-it/   /' | sed 's/-en/   /' | sed 's/-fr/   /' | sed 's/-sp/   /' | sed 's/ \./  /' | sed "s|$OldRversion_C||")
-[ "$ORI" != "y" ] && echo "New recoverversion: .$New_Rversion."
+##[ "$ORI" != "y" ] && echo "New recoverversion: .$New_Rversion."
 #echo "Old recoverversion : .$OldRversion."
 #echo "Old recoverversionC: .$OldRversion_C."
-[ "$ORI" != "y" ] && sed -i -e "s|$OldRversion|$New_Rversion|" "$output_dir/exe_mid"
+##[ "$ORI" != "y" ] && sed -i -e "s|$OldRversion|$New_Rversion|" "$output_dir/exe_mid"
 
 dd if=/dev/zero bs=1 count=$act_diff >$output_dir/zerro.image 2> /dev/null
 #echo "concat all parts ..."
@@ -243,7 +233,7 @@ act_size=`ls -l "$input_recover_file" | sed -e 's/[^0-9]/#/g' | sed -e 's/#\+[0-
 new_act_size=`ls -l "$new_recover_file" | sed -e 's/[^0-9]/#/g' | sed -e 's/#\+[0-9]\+#\+\([0-9]\+\).*/\1/'`
 #echo "actual size= $act_size,  new actual size= $new_act_size" 
 [ $act_size -eq $new_act_size ] || echo "ERROR! Reduce size of kernel.image by: $error_size Bytes." 
-[ $act_size -eq $new_act_size ] && [ -f "$new_recover_file" ] && echo -e "New Recover:\n$new_recover_file\n\
+[ $act_size -eq $new_act_size ] && [ -f "$new_recover_file" ] && echo -e "New Recover: $new_recover_file\n\
 Transfer this file to windows and start it to push the new firmware to your router.\n\
 This is the 3rd method to update Firmware, in most cases this will be the most \n\
 reliable way to do a firmware update.\n\
