20100903-0757 - only text changes
git-svn-id: https://svn.code.sf.net/p/freetzlinux/code@1035 fc5b469a-3574-4ed2-a3ea-762ab7856fab

diff --git a/trunk/speed-to-fritz/build_new_recover_firmware b/trunk/speed-to-fritz/build_new_recover_firmware
--- a/trunk/speed-to-fritz/build_new_recover_firmware
+++ b/trunk/speed-to-fritz/build_new_recover_firmware
@@ -180,20 +180,20 @@ sed -i -e 's|\x85\xC0\x59\x0F\x85\xFA\x01\x00\x00\x8D\x85|\x85\xC0\x59\x90\x90\x
 -e 's|\x00\x3B\xC8\x73\x4A\x8D\x95|\x00\x3B\xC8\xEB\x4A\x8D\x95|' "$output_dir/exe_start"
 #0x1a5f0 .26 firmware
 #sed -i -e 's|734A8D951CFCFFFF525150684C619000|EB4A8D951CFCFFFF525150684C619000|' "./$output_dir/exe_start"
-$RDIR/ipsr s "0x9090909090908d85" "$output_dir/exe_start" || ( echo "-- Firmware version check remove error!" && checkerror="y" )
+$RDIR/ipsr s "0x9090909090908d85" "$output_dir/exe_start" || ( echo "-- firmware version check remove error!" && checkerror="y" )
 $RDIR/ipsr s "0x909090909090399d" "$output_dir/exe_start" || ( echo "-- OEM check remove error!" && checkerror="y" )
-$RDIR/ipsr s "0xeb5983ffff89bd" "$output_dir/exe_start" || ( echo "-- Kernel check remove error!" && checkerror="y" )
+$RDIR/ipsr s "0xeb5983ffff89bd" "$output_dir/exe_start" || ( echo "-- kernel check remove error!" && checkerror="y" )
 #$RDIR/ipsr s "0xc40c85c0eb4a" "$output_dir/exe_start" || ( echo "-- CRC check remove error!" && checkerror="y" )
 #$RDIR/ipsr   "0x7300909050b68f00" "$output_dir/exe_start" || ( echo "-- Urloader update remove error!" && checkerror="y" )
 ( $RDIR/ipsr s "0x720881ffe8030000" "$output_dir/exe_start" || \
-$RDIR/ipsr s "0x7205397D08730689" "$output_dir/exe_start" ) || ( echo "-- Urloader2 update remove error!" && checkerror="y" )
+$RDIR/ipsr s "0x7205397D08730689" "$output_dir/exe_start" ) || ( echo "-- urloader2 update remove error!" && checkerror="y" )
 #rplbytes="0xeb4a8d951cfcffff525150684c619000"
 #$RDIR/ipsr s "0xeb4a8d951cfcffff525150684c619000" "$output_dir/exe_start" || ( echo "-- Check kernel size remove error!" && checkerror="y" )
 if ! ( [ "${R_IMG}" == "${RECOVERIMG7140}" ] || [ "${R_IMG}" == "${RECOVERIMG5050}" ] ) ; then
  {
- $RDIR/ipsr s "0x003bc8eb4a8d95" "$output_dir/exe_start" || ( echo "-- Check kernel size remove error!" && checkerror="y" )
+ $RDIR/ipsr s "0x003bc8eb4a8d95" "$output_dir/exe_start" || ( echo "-- check kernel size remove error!" && checkerror="y" )
  ( $RDIR/ipsr s "0xeb488d8508" "$output_dir/exe_start" || \
- $RDIR/ipsr s "0xeb458d8510" "$output_dir/exe_start" ) ||  ( echo "-- Check2 kernel size remove error!" && checkerror="y" )
+ $RDIR/ipsr s "0xeb458d8510" "$output_dir/exe_start" ) ||  ( echo "-- check2 kernel size remove error!" && checkerror="y" )
  }
 fi
 act_size=`ls -l "$output_dir/kernel.image" | sed -e 's/[^0-9]/#/g' | sed -e 's/#\+[0-9]\+#\+\([0-9]\+\).*/\1/'`
@@ -204,7 +204,7 @@ error_size=$((new_act_size - act_size))
 [ -n "$kernel_size" ] && [ "$act_size" -lt "$kernel_size" ] && kernel_diff_size=$((kernel_size - act_size))
 if [ $act_size -lt $new_act_size ]; then
     echo "ERROR!! New kernel.image does not fit into recover firmware." && checkerror="y"
-    [ -n "$kernel_size" ] && [ "$kernel_diff_size" -gt 0 ] && echo  "Space within the recover firmware is smaller as in the flash by: $kernel_diff_size Bytes."
+    [ -n "$kernel_size" ] && [ "$kernel_diff_size" -gt 0 ] && echo  "--  space within the recover firmware is smaller as in the flash by: $kernel_diff_size Bytes."
 fi
 
 AVM_New_version="$AVM_VERSION_MAJOR.$AVM_VERSION"
