* W920: Revert misstake made in revision 1318 http://www.ip-phone-forum.de/showthread.php?t=203794&p=1724461&viewfull=1#post1724461
git-svn-id: https://svn.code.sf.net/p/freetzlinux/code@1342 fc5b469a-3574-4ed2-a3ea-762ab7856fab

diff --git a/trunk/speed-to-fritz/Speedport920 b/trunk/speed-to-fritz/Speedport920
--- a/trunk/speed-to-fritz/Speedport920
+++ b/trunk/speed-to-fritz/Speedport920
@@ -12,27 +12,28 @@ echo -e "\033[1m${SORCE_PRODUKT}  --->   ${CONFIG_PRODUKT}\033[0m "
 fi
 #Attention! Vinax uses aditional /dev/vinax device entrys the are generateed via /tools/device_table.txt (makedevice option)
 cp -fdrp "${DST}"/dev --target-directory="${SRC}" #this copy is only usable if run as root
-[ "${FORCE_TCOM_KDSLDMOD}" = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/dsld
-[ "${FORCE_TCOM_PCMLINK}" = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/char/ubik2/pcmlink.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/char/ubik2
-[ "${FORCE_TCOM_USRMAN}" = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/userman/userman_mod.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/driver/userman
+[ "${FORCE_TCOM_KDSLDMOD}" = "y" ] && cp -fdrp $VERBOSE "${DST}"/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/dsld  | sed "s/.*\//\tuse original '/"
+[ "${FORCE_TCOM_PCMLINK}" = "y" ] && cp -fdrp $VERBOSE "${DST}"/lib/modules/$KernelVersion/kernel/drivers/char/ubik2/pcmlink.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/char/ubik2 | sed "s/.*\//\tuse original '/" &&\
+[ "${FORCE_TCOM_USRMAN}" = "y" ] && cp -fdrp $VERBOSE "${DST}"/lib/modules/$KernelVersion/kernel/drivers/userman/* --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/driver/userman  | sed "s/.*\//\tuse original '/" &&\
 if [ "${TYPE_AVM_7570_XX}" = "y" ]; then
+ echo2 "-- 3nd firmware is 7570 type"
  if [ "${SAVE_TCOM_DSL}" = "y" ]; then
     cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko ./addon/tmp/W920/squashfs-root/lib/modules/vinax/drv_vinax.ko &&\
-    echo "-- VINAX driver saved to: ./addon/tmp/W920/..."
+    echo "-- VINAX drv_vinax.ko driver saved to: ./addon/tmp/W920/..."
  fi
  if [ "${SAVE_SRC2_DSL}" = "y" ]; then
     cp -fdrp "${SRC_2}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko ./addon/tmp/W920/squashfs-root/lib/modules/vinax/drv_vinax.ko &&\
-    echo "-- VINAX driver saved to: ./addon/tmp/W920/..."
+    echo "-- VINAX drv_vinax.ko driver saved to: ./addon/tmp/W920/..."
  fi
  if [ "${USE_SRC2_DSL}" = "y" ]; then
     cp -fdrp "${SRC_2}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko "${SRC}/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko" &&\
-    echo "-- VINAX driver was taken from 2nd AVM firmware"
+    echo "-- VINAX drv_vinax.ko driver was taken from 2nd AVM firmware"
  elif [ "${USE_OWN_DSL}" = "y" ]; then
     cp -fdrp ./addon/tmp/W920/squashfs-root/lib/modules/vinax/drv_vinax.ko "${SRC}/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko" &&\
-    echo "-- VINAX driver was taken from the original base firmware"
+    echo "-- VINAX drv_vinax.ko driver was taken from the original base firmware"
  elif [ "${FORCE_TCOM_DSL}" = "y" ]; then
     cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko "${SRC}/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko" &&\
-    echo "-- VINAX driver was taken from the original base firmware"
+    echo "-- VINAX drv_vinax.ko driver was taken from the original base firmware"
  fi
 else
  # "vinax_fw_adsl.bin" "vinax_fw_vdsl.bin"
@@ -40,6 +41,16 @@ else
  rm -fdr "${SRC}"/lib/modules/dsp_ur8
  rm -fdr "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/dsl
  # "vinax_driver"
+ [ -d "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax ] || mkdir "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax
+ [ -d "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax ] || mkdir "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax
+ cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax
+ cp -fdrp "${DST}"/lib/modules/$KernelVersion/modules.symbols --target-directory="${SRC}"/lib/modules/$KernelVersion
+ cp -fdrp "${DST}"/lib/modules/$KernelVersion/modules.alias --target-directory="${SRC}"/lib/modules/$KernelVersion
+ cp -u "${DST}"/usr/sbin/* --target-directory="${SRC}"/usr/sbin 2> /dev/null
+ cp -fdrp "${DST}"/lib/modules/vinax* --target-directory="${SRC}"/lib/modules &&\
+ echo "-- DSL driver was taken from the original base firmware"
+ [ -f "${SRC}"/usr/share/ctlmgr/libvdsl.so ] || cp -fdrp "${DST}"/usr/share/ctlmgr/libvdsl.so --target-directory="${SRC}"/usr/share/ctlmgr
+ [ -f "${SRC}"/usr/share/ctlmgr/libtr064.so ] || cp -fdrp "${DST}"/usr/share/ctlmgr/libtr064.so --target-directory=${SRC}/usr/share/ctlmgr
 
  if [ "${SAVE_TCOM_DSL}" = "y" ]; then
     cp -fdrp "${DST}"/lib/modules/vinax* --target-directory=./addon/tmp/W920/squashfs-root/lib/modules &&\
@@ -76,26 +87,31 @@ else
     [ -f "${SRC}"/usr/share/ctlmgr/libvdsl.so ] || cp -fdrp "${SRC_2}"/usr/share/ctlmgr/libvdsl.so --target-directory="${SRC}"/usr/share/ctlmgr
     [ -f "${SRC}"/usr/share/ctlmgr/libtr064.so ] || cp -fdrp "${SRC_2}"/usr/share/ctlmgr/libtr064.so --target-directory=${SRC}/usr/share/ctlmgr
     cp -fdrp "${SRC_2}"/lib/modules/vinax* --target-directory="${SRC}"/lib/modules &&\
-    echo "-- DSL driver was taken from 3. firmware"
+    echo "-- DSL driver was taken from 2nd AVM firmware"
  fi
 fi
-
 
 [ "${USE_OWN_DSL}" = "y" ] && cp -fdrp ./addon/tmp/W920/squashfs-root/* --target-directory="${SRC}" &&\
 echo "-- VINAX DSL driver was taken from local directory ./addon/tmp/W920"
 if [ "${SAVE_SRC2_KDSLDMOD}" = "y" ]; then
     mkdir -p ./addon/tmp/W920/squashfs-root/lib/modules/$KernelVersion/kernel/drivers/dsld
     cp -fdrp "${SRC_2}"/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory=./addon/tmp/W920/squashfs-root/lib/modules/$KernelVersion/kernel/drivers/dsld &&\
-    echo "-- 2nd AVM Firmware kdslmod driver saved to: ./addon/tmp/W920"
+    echo "-- 2nd AVM Firmware kdslmod.ko driver saved to: ./addon/tmp/W920"
 fi
 [ "${FORCE_SRC2_KDSLDMOD}" = "y" ] && cp -fdrp "${SRC_2}"/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/dsld &&\
-echo "-- kdslmod driver was taken from 2nd AVM source."
+echo "-- kdslmod.ko driver was taken from 2nd AVM source."
 
 if [ "${FORCE_OWN_KDSLDMOD}" = "y" ] && ! [ -f ./addon/tmp/W920/squashfs-root/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko ]; then
  echo "You must save kdsld driver form 2nd AVM source before" && sleep 10 && exit 1
 fi
 [ "${FORCE_OWN_KDSLDMOD}" = "y" ] && cp -fdrp ./addon/tmp/W920/squashfs-root/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory="${SRC}/lib/modules/$KernelVersion/kernel/drivers/dsld" &&\
-echo "-- kdslmod driver was taken from local directory ./addon/tmp/W920"
+echo "-- kdslmod.ko driver was taken from local directory ./addon/tmp/W920"
+
+[ "${FORCE_VINAX_DRV_77}" = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko --target-directory="${SRC}/lib/modules/$KernelVersion/kernel/drivers/vinax" &&\
+echo "-- drv_vinax.ko was taken from 1st source (base firmware)."
+[ "${FORCE_KDSLD_DRV_77}" = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory="${SRC}/lib/modules/$KernelVersion/kernel/drivers/dsld" &&\
+echo "-- kdsldmod.ko was taken from 1st source (base firmware)."
+
 
 rm -rf "${SRC}"/lib/modules/*_488.hex
 if [ "${SAVE_SRC2_DECTDRIVER}" = "y" ]; then
@@ -116,15 +132,8 @@ echo "-- DECT driver was taken from local directory ./addon/tmp/W920"
 if `cat "${SRC}/etc/init.d/rc.S" | grep -q '_488.hex' ` && ! [ -f "${SRC}"/lib/modules/dectfw_firstlevel.hex ]; then
  echo "You must use dect driver form 2nd AVM source or one that was saved before" && sleep 10 && exit 1
 fi
-[ "${FORCE_VINAX_DRV}" = "y" ] && cp -fdrp ${HOMEDIR}/addon/tmp/modules/vinax/drv_vinax.ko --target-directory="${SRC}/lib/modules/$KernelVersion/kernel/drivers/vinax" &&\
-echo "-- PPPoA compatible VINAX DSL driver is in use!"
-[ "${FORCE_KDSLD_DRV}" = "y" ] && cp -fdrp ${HOMEDIR}/addon/tmp/modules/dsld/kdsldmod.ko --target-directory="${SRC}/lib/modules/$KernelVersion/kernel/drivers/dsld" &&\
-echo "-- PPPoA compatible KDSLDMOD driver is in use!"
 
-[ "${FORCE_VINAX_DRV_77}" = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko --target-directory="${SRC}/lib/modules/$KernelVersion/kernel/drivers/vinax" &&\
-echo "-- compatible VINAX DSL driver is in use!"
-[ "${FORCE_KDSLD_DRV_77}" = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory="${SRC}/lib/modules/$KernelVersion/kernel/drivers/dsld" &&\
-echo "-- compatible KDSLDMOD driver is in use!"
+
 #v3 dect fix
 grep -q "488" "${SRC}/etc/init.d/rc.S" && \
 echo "-- 7270v3 firmware" && \
@@ -220,15 +229,6 @@ if [ -f "${DST}"/lib/modules/$KernelVersion/kernel/drivers/char/led_module.ko ] 
     cp -fdrp "${DST}"/bin/led* --target-directory="${SRC}"/bin
     cp -fr "${DST}"/bin/update_led_on ${SRC}/bin/update_led_on
     cp -fr "${DST}"/bin/update_led_off ${SRC}/bin/update_led_off
- [ -d "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax ] || mkdir "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax
- cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax
- cp -fdrp "${DST}"/lib/modules/$KernelVersion/modules.symbols --target-directory="${SRC}"/lib/modules/$KernelVersion
- cp -fdrp "${DST}"/lib/modules/$KernelVersion/modules.alias --target-directory="${SRC}"/lib/modules/$KernelVersion
- cp -u "${DST}"/usr/sbin/* --target-directory="${SRC}"/usr/sbin 2> /dev/null
- cp -fdrp "${DST}"/lib/modules/vinax* --target-directory="${SRC}"/lib/modules &&\
- echo "-- DSL driver was taken from the original base firmware"
- [ -f "${SRC}"/usr/share/ctlmgr/libvdsl.so ] || cp -fdrp "${DST}"/usr/share/ctlmgr/libvdsl.so --target-directory="${SRC}"/usr/share/ctlmgr
- [ -f "${SRC}"/usr/share/ctlmgr/libtr064.so ] || cp -fdrp "${DST}"/usr/share/ctlmgr/libtr064.so --target-directory=${SRC}/usr/share/ctlmgr
     echo "-- LED driver was taken from the original base firmware"
 fi
 if [ -f "${SRC_2}"/lib/modules/$KernelVersion/kernel/drivers/char/led_module.ko ] && [ "${FORCE_SRC2_LEDDRIVER}" = "y" ]; then
@@ -339,6 +339,8 @@ echo "-- DSL Annex B driver was removed from ${SORCE_PRODUKT}!"
 #save space
 [ "${REMOVE_ANNEX_A_DSL_DRIVER}" = "y" ] && [ -f "${SRC}/lib/modules/vinax_fw_adsl_A.bin" ] && rm -f "${SRC}"/lib/modules/vinax_fw_adsl_A.bin &&\
 echo "-- DSL Annex A driver was removed from ${SORCE_PRODUKT}!"
+! [ -f ${SRC}/lib/modules/vinax_fw_vdsl.bin ] && echo "VINAX vdsl driver is missing!" && sleep 10 && exit 1
+! [ -f ${SRC}/lib/modules/vinax_fw_adsl_A.bin ] && ! [ -f ${SRC}/lib/modules/vinax_fw_adsl_A.bin ] && echo "VINAX vdsl driver is missing!" && sleep 10 && exit 1
 #fix ADSL interface accsess restrictions
 sed -i -e "/ \/etc\/init.d\/rc.conf/a\
 \[ -f \/var\/flash\/ar7.cfg \] \&\& sed -i -e 's|ifacectl|hprio|' \/var\/flash\/ar7.cfg \&\& cat \/var\/flash\/ar7.cfg | grep ifacectl \&\& echo '---- Not fixed ADSL ---'" "${SRC}/etc/init.d/rc.S"
